WIP: feat(ava): 初始化增加insight mark
antvis/g2-extentions pull request #6
Opened 2023-11-02 14:39 UTC by chenluli

增加 insight mark
例如在折线图上增加异动区间和异常点
```
{
    type: 'view',
    children: [
      // 原始图表
      {
        data: { type: "fetch", value: "data/basic-time-series.csv" },
        encode: {
            "x": "year",
            "y": "life_expect"
        },
        type: "line",
        style: {
            "lineWidth": 2
        }
      },
      // 洞察展示 mark
      {
        type: "insight",
        data: { type: "fetch", value: "data/basic-time-series.csv" },
        // 指定分析的维度、指标和分析类型
        measures: [
          { fieldName: 'life_expect', method: 'MEAN' },
        ],
        dimensions: ['year'],
        insightType: 'time_series_outlier',
      },
    ]
  };
}
```
<img width="616" alt="Screenshot 2023-11-02 at 10 30 32 PM" src="https://github.com/antvis/g2-extentions/assets/16997933/8e35093a-1f8e-4a2c-8378-c541bcd1c8b0">

2023-11-03 06:17 UTC, pearmini requested changes

2023-11-03 06:17 UTC, pearmini commented on ava/__tests__/plots/time-series-outlier-basic.ts
> +        insightType: 'time_series_outlier',
Insight 的 measure 和 dimension 配置变成 encode，和 Line Mark 一样会好一点？这样 encode 可以声明在 view，最后 spec 如下：

```js
const options = {
  type: 'view',
  data: { type: "fetch", value: "data/basic-time-series.csv" },
  encode: { x: 'year', y: 'life_expect' }, 
  children: [
    { type: 'line' },
    { type: 'insight' }
  ]
}
```

2023-11-03 08:36 UTC, chenluli commented on ava/__tests__/plots/time-series-outlier-basic.ts
> +        insightType: 'time_series_outlier',
有两个问题
1. insight mark 这里能拿到 view 层的数据吗，我这里看好像这个 options 只能拿到 insight 下面的数据
<img width="524" alt="Screenshot 2023-11-03 at 4 33 06 PM" src="https://github.com/antvis/g2-extentions/assets/16997933/1959c272-7fb7-40a7-99fd-60eb99241c59">

2. 指标有指定聚合方式，比如是“平均”、“求和”、“最大/最小值” 如果不要求用户指定的话，可能需要从 view 里或者 line 里的 transform 之类的推断？

2023-11-10 08:14 UTC, chenluli commented on ava/__tests__/plots/time-series-outlier-basic.ts
> +        insightType: 'time_series_outlier',
已修改为支持 encode 写法

2023-11-10 08:15 UTC, pearmini approved these changes

2023-11-10 08:41 UTC, merged